export interface Airport {
  code: string;
  cityAr: string;
  cityEn: string;
  countryAr: string;
  countryEn: string;
}

export const airports: Airport[] = [
  // Saudi Arabia
  { code: "JED", cityAr: "جدة", cityEn: "Jeddah", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  { code: "RUH", cityAr: "الرياض", cityEn: "Riyadh", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  { code: "DMM", cityAr: "الدمام", cityEn: "Dammam", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  { code: "MED", cityAr: "المدينة", cityEn: "Madinah", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  { code: "AHB", cityAr: "أبها", cityEn: "Abha", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  { code: "GIZ", cityAr: "جازان", cityEn: "Gizan", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  { code: "TIF", cityAr: "الطائف", cityEn: "Taif", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  { code: "ELQ", cityAr: "القصيم", cityEn: "Gassim", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  { code: "HOF", cityAr: "الهفوف", cityEn: "Al Hofuf", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  { code: "YNB", cityAr: "ينبع", cityEn: "Yanbu", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  { code: "TUU", cityAr: "تبوك", cityEn: "Tabuk", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  { code: "HAS", cityAr: "حائل", cityEn: "Hail", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  { code: "AJF", cityAr: "الجوف", cityEn: "Al Jouf", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  { code: "EAM", cityAr: "نجران", cityEn: "Najran", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  { code: "BHH", cityAr: "بيشة", cityEn: "Bisha", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  { code: "WAE", cityAr: "وادي الدواسر", cityEn: "Wadi Al Dawasir", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  { code: "DWD", cityAr: "الدوادمي", cityEn: "Dawadmi", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  { code: "RAH", cityAr: "رفحا", cityEn: "Rafha", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  { code: "URY", cityAr: "القريات", cityEn: "Gurayat", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  { code: "TUI", cityAr: "طريف", cityEn: "Turaif", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  { code: "ABT", cityAr: "الباحة", cityEn: "Al Baha", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  { code: "SHW", cityAr: "شرورة", cityEn: "Sharurah", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  { code: "DHA", cityAr: "الظهران", cityEn: "Dhahran", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  { code: "HBT", cityAr: "حفر الباطن", cityEn: "Hafar Al Batin", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  { code: "AQI", cityAr: "القيصومة", cityEn: "Al Qaisumah", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  { code: "KMC", cityAr: "المدينة العسكرية", cityEn: "King Khaled Military City", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  { code: "RAE", cityAr: "عرعر", cityEn: "Arar", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  { code: "EJH", cityAr: "الوجه", cityEn: "Al Wajh", countryAr: "السعودية", countryEn: "Saudi Arabia" },
  
  // GCC & Middle East
  { code: "DXB", cityAr: "دبي", cityEn: "Dubai", countryAr: "الإمارات", countryEn: "UAE" },
  { code: "AUH", cityAr: "أبوظبي", cityEn: "Abu Dhabi", countryAr: "الإمارات", countryEn: "UAE" },
  { code: "SHJ", cityAr: "الشارقة", cityEn: "Sharjah", countryAr: "الإمارات", countryEn: "UAE" },
  { code: "BAH", cityAr: "المنامة", cityEn: "Manama", countryAr: "البحرين", countryEn: "Bahrain" },
  { code: "KWI", cityAr: "الكويت", cityEn: "Kuwait", countryAr: "الكويت", countryEn: "Kuwait" },
  { code: "DOH", cityAr: "الدوحة", cityEn: "Doha", countryAr: "قطر", countryEn: "Qatar" },
  { code: "MCT", cityAr: "مسقط", cityEn: "Muscat", countryAr: "عمان", countryEn: "Oman" },
  { code: "SLL", cityAr: "صلالة", cityEn: "Salalah", countryAr: "عمان", countryEn: "Oman" },
  { code: "CAI", cityAr: "القاهرة", cityEn: "Cairo", countryAr: "مصر", countryEn: "Egypt" },
  { code: "HBE", cityAr: "برج العرب", cityEn: "Borg El Arab", countryAr: "مصر", countryEn: "Egypt" },
  { code: "SSH", cityAr: "شرم الشيخ", cityEn: "Sharm El Sheikh", countryAr: "مصر", countryEn: "Egypt" },
  { code: "HRG", cityAr: "الغردقة", cityEn: "Hurghada", countryAr: "مصر", countryEn: "Egypt" },
  { code: "LXR", cityAr: "الأقصر", cityEn: "Luxor", countryAr: "مصر", countryEn: "Egypt" },
  { code: "AMM", cityAr: "عمان", cityEn: "Amman", countryAr: "الأردن", countryEn: "Jordan" },
  { code: "AQJ", cityAr: "العقبة", cityEn: "Aqaba", countryAr: "الأردن", countryEn: "Jordan" },
  { code: "BEY", cityAr: "بيروت", cityEn: "Beirut", countryAr: "لبنان", countryEn: "Lebanon" },
  { code: "DAM", cityAr: "دمشق", cityEn: "Damascus", countryAr: "سوريا", countryEn: "Syria" },
  { code: "BGW", cityAr: "بغداد", cityEn: "Baghdad", countryAr: "العراق", countryEn: "Iraq" },
  { code: "EBL", cityAr: "أربيل", cityEn: "Erbil", countryAr: "العراق", countryEn: "Iraq" },
  { code: "BSR", cityAr: "البصرة", cityEn: "Basra", countryAr: "العراق", countryEn: "Iraq" },
  { code: "SAH", cityAr: "صنعاء", cityEn: "Sana'a", countryAr: "اليمن", countryEn: "Yemen" },
  { code: "ADE", cityAr: "عدن", cityEn: "Aden", countryAr: "اليمن", countryEn: "Yemen" },
  { code: "IST", cityAr: "إسطنبول", cityEn: "Istanbul", countryAr: "تركيا", countryEn: "Turkey" },
  
  // International
  { code: "LHR", cityAr: "لندن", cityEn: "London", countryAr: "المملكة المتحدة", countryEn: "UK" },
  { code: "MAN", cityAr: "مانشستر", cityEn: "Manchester", countryAr: "المملكة المتحدة", countryEn: "UK" },
  { code: "CDG", cityAr: "باريس", cityEn: "Paris", countryAr: "فرنسا", countryEn: "France" },
  { code: "FRA", cityAr: "فرانكفورت", cityEn: "Frankfurt", countryAr: "ألمانيا", countryEn: "Germany" },
  { code: "MUC", cityAr: "ميونخ", cityEn: "Munich", countryAr: "ألمانيا", countryEn: "Germany" },
  { code: "FCO", cityAr: "روما", cityEn: "Rome", countryAr: "إيطاليا", countryEn: "Italy" },
  { code: "MXP", cityAr: "ميلان", cityEn: "Milan", countryAr: "إيطاليا", countryEn: "Italy" },
  { code: "MAD", cityAr: "مدريد", cityEn: "Madrid", countryAr: "إسبانيا", countryEn: "Spain" },
  { code: "BCN", cityAr: "برشلونة", cityEn: "Barcelona", countryAr: "إسبانيا", countryEn: "Spain" },
  { code: "JFK", cityAr: "نيويورك", cityEn: "New York", countryAr: "أمريكا", countryEn: "USA" },
  { code: "IAD", cityAr: "واشنطن", cityEn: "Washington", countryAr: "أمريكا", countryEn: "USA" },
  { code: "LAX", cityAr: "لوس أنجلوس", cityEn: "Los Angeles", countryAr: "أمريكا", countryEn: "USA" },
  { code: "YYZ", cityAr: "تورنتو", cityEn: "Toronto", countryAr: "كندا", countryEn: "Canada" },
  { code: "BOM", cityAr: "مومباي", cityEn: "Mumbai", countryAr: "الهند", countryEn: "India" },
  { code: "DEL", cityAr: "دلهي", cityEn: "Delhi", countryAr: "الهند", countryEn: "India" },
  { code: "COK", cityAr: "كوتشي", cityEn: "Kochi", countryAr: "الهند", countryEn: "India" },
  { code: "HYD", cityAr: "حيدر أباد", cityEn: "Hyderabad", countryAr: "الهند", countryEn: "India" },
  { code: "MAA", cityAr: "شيناي", cityEn: "Chennai", countryAr: "الهند", countryEn: "India" },
  { code: "BLR", cityAr: "بنغالور", cityEn: "Bangalore", countryAr: "الهند", countryEn: "India" },
  { code: "CCJ", cityAr: "كاليكوت", cityEn: "Calicut", countryAr: "الهند", countryEn: "India" },
  { code: "LHE", cityAr: "لاهور", cityEn: "Lahore", countryAr: "باكستان", countryEn: "Pakistan" },
  { code: "ISB", cityAr: "إسلام أباد", cityEn: "Islamabad", countryAr: "باكستان", countryEn: "Pakistan" },
  { code: "KHI", cityAr: "كراتشي", cityEn: "Karachi", countryAr: "باكستان", countryEn: "Pakistan" },
  { code: "PEW", cityAr: "بيشاور", cityEn: "Peshawar", countryAr: "باكستان", countryEn: "Pakistan" },
  { code: "DAC", cityAr: "دكا", cityEn: "Dhaka", countryAr: "بنغلاديش", countryEn: "Bangladesh" },
  { code: "CGK", cityAr: "جاكرتا", cityEn: "Jakarta", countryAr: "إندونيسيا", countryEn: "Indonesia" },
  { code: "KUL", cityAr: "كوالالمبور", cityEn: "Kuala Lumpur", countryAr: "ماليزيا", countryEn: "Malaysia" },
  { code: "MNL", cityAr: "مانيلا", cityEn: "Manila", countryAr: "الفلبين", countryEn: "Philippines" },
  { code: "BKK", cityAr: "بانكوك", cityEn: "Bangkok", countryAr: "تايلاند", countryEn: "Thailand" },
  { code: "CAN", cityAr: "جوانزو", cityEn: "Guangzhou", countryAr: "الصين", countryEn: "China" },
  { code: "TUN", cityAr: "تونس", cityEn: "Tunis", countryAr: "تونس", countryEn: "Tunisia" },
  { code: "CMN", cityAr: "الدار البيضاء", cityEn: "Casablanca", countryAr: "المغرب", countryEn: "Morocco" },
  { code: "ALG", cityAr: "الجزائر", cityEn: "Algiers", countryAr: "الجزائر", countryEn: "Algeria" },
  { code: "KRT", cityAr: "الخرطوم", cityEn: "Khartoum", countryAr: "السودان", countryEn: "Sudan" },
  { code: "ADD", cityAr: "أديس أبابا", cityEn: "Addis Ababa", countryAr: "إثيوبيا", countryEn: "Ethiopia" },
];
